CREATE TABLE SETUP.USERLOGINLOGDETAIL
(
RowId						BIGINT IDENTITY(1,1)
,Id							VARCHAR(250) PRIMARY KEY  DEFAULT (NEWID())
,UserId						VARCHAR(250) FOREIGN KEY REFERENCES SETUP.USERDETAIL(Id)
,LoginDate					DATETIME
,IPAddress					VARCHAR(250)
,CreatedBy					VARCHAR(250)
,CreatedDateLocal			DATETIME
,CreatedDateUTC				DATETIME
)
